# This workflow is designed to add the current date to a README.md file and then remove it later.
# It's scheduled to run twice a day using cron.

name: Daily README Update

# This workflow will run on a schedule
on:
  schedule:
    # This runs the 'add-date' job daily at 00:00 UTC (12 AM)
    - cron: '0 0 * * *'
    # This runs the 'remove-date' job daily at 23:59 UTC (11:59 PM)
    - cron: '59 23 * * *'

jobs:
  # Job to add the current date to the README file
  add-date:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 0 * * *'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions-bot@users.noreply.github.com"
          
      - name: Get current date
        id: date
        run: echo "current_date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        
      - name: Check if date is already in README
        id: check_date
        run: |
          if ! grep -q "Current Date Added by Workflow: ${{ steps.date.outputs.current_date }}" README.md; then
            echo "::set-output name=should_update::true"
          else
            echo "::set-output name=should_update::false"
          fi
          
      - name: Add date to README
        if: steps.check_date.outputs.should_update == 'true'
        run: echo "Current Date Added by Workflow: ${{ steps.date.outputs.current_date }}" >> README.md
        
      - name: Commit and push changes
        if: steps.check_date.outputs.should_update == 'true'
        run: |
          git add README.md
          git commit -m "chore: Add current date to README.md"
          git push

  # Job to remove the date from the README file
  remove-date:
    runs-on: ubuntu-latest
    if: github.event.schedule == '59 23 * * *'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions-bot@users.noreply.github.com"
          
      - name: Remove date from README
        # Using sed to find the line that contains the "Current Date Added by Workflow" string and delete it.
        # The -i flag edits the file in place.
        run: sed -i '/^Current Date Added by Workflow:/d' README.md
        
      - name: Check if changes were made
        id: git-status
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "::set-output name=changes_made::true"
          else
            echo "::set-output name=changes_made::false"
          fi
          
      - name: Commit and push changes
        if: steps.git-status.outputs.changes_made == 'true'
        run: |
          git add README.md
          git commit -m "chore: Remove date from README.md"
          git push
